FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

EXPOSE 3000

CMD ["sh", "docker/entrypoint.dev.sh"]